# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Scenario Oriented Object Navigation (SOON)
short_description: Scenario Oriented Object Navigation (SOON) is an embodied object navigation task, where an agent is required to navigate from an arbitrary position in a 3D embodied environment to localize a target following a scene description. 
# description: The ability to navigate like a human towards a language-guided target from anywhere in a 3D embodied environment is one of the "holy grail" goals of intelligent robots. We introduce a Scenario Oriented Object Navigation (SOON) task, where an agent is required to navigate from an arbitrary position in a 3D embodied environment to localize a target following a scene description. A description includes object attribute, object relationship, region description, and nearby region description.
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: 
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2021-06-22 00:00:00
end_date: 2021-8-22 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["length", "OSR", "SR", "SPL", "SFPL"],
        "default_order_by": "SFPL",
      }

challenge_phases:
  - id: 1
    name: Val Unseen House Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2021-06-22 00:00:00
    end_date: 2021-08-22 23:59:59
    test_annotation_file: annotations/val_unseen_house.json
    codename: val_unseen
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json"
  - id: 2
    name: Test Minival Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2021-06-22 00:00:00
    end_date: 2021-08-22 23:59:59
    test_annotation_file: annotations/test.json
    codename: test
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json"
  # - id: 3
  #   name: Dev Phase 3
  #   description: templates/challenge_phase_1_description.html
  #   leaderboard_public: False
  #   is_public: True
  #   is_submission_public: True
  #   start_date: 2019-06-22 00:00:00
  #   end_date: 2099-08-22 23:59:59
  #   test_annotation_file: annotations/val_unseen_house.json
  #   codename: dev3
  #   max_submissions_per_day: 5
  #   max_submissions_per_month: 50
  #   max_submissions: 50
  #   default_submission_meta_attributes:
  #     - name: method_name
  #       is_visible: True
  #     - name: method_description
  #       is_visible: True
  #     - name: project_url
  #       is_visible: True
  #     - name: publication_url
  #       is_visible: True
  #   is_restricted_to_select_one_submission: False
  #   is_partial_submission_evaluation_enabled: False
  #   allowed_submission_file_types: ".json"

dataset_splits:
  - id: 1
    name: Val Unseen House Split
    codename: val_unseen_split
  - id: 2
    name: Test Minival Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 2
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  # - challenge_phase_id: 3
  #   leaderboard_id: 1
  #   dataset_split_id: 2
  #   visibility: 1
  #   leaderboard_decimal_precision: 2
  #   is_leaderboard_order_descending: True
